<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="145393" started-at="2019-01-11T09:39:22Z" finished-at="2019-01-11T09:41:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="145393" started-at="2019-01-11T09:39:22Z" finished-at="2019-01-11T09:41:47Z">
      <class name="executableClass.Static_Infobar_loggedin_Users">
        <test-method status="FAIL" signature="TC001_Staticbar_links_Hardlogin()[pri:1, instance:executableClass.Static_Infobar_loggedin_Users@14bf9759]" name="TC001_Staticbar_links_Hardlogin" duration-ms="145207" started-at="2019-01-11T15:09:22Z" finished-at="2019-01-11T15:11:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error in hardlogin page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error in hardlogin page
	at org.testng.Assert.fail(Assert.java:94)
	at computedClass.Computed_HardLogin.Global_HardLogin(Computed_HardLogin.java:71)
	at executableClass.Static_Infobar_loggedin_Users.TC001_Staticbar_links_Hardlogin(Static_Infobar_loggedin_Users.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:150)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Staticbar_links_Hardlogin -->
      </class> <!-- executableClass.Static_Infobar_loggedin_Users -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
